version: '3.9'

services:
  api:
    build:
      context: ./WebShop.Api
      dockerfile: Dockerfile
    ports:
      - "5085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./WebShop.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
